package com.app.toga;

import java.util.ArrayList;

public class DataToga {


    public static String[][] datatoga = new  String[][]{
            {"KUNYIT", "Deskripsi Singkat :\n\nKunyit atau Curcuma domestica Val biasanya digunakan sebagai bumbu dapur atau yang biasanya digunakan oleh masyarakat Bangka Belitung untuk membuat masakan lempah kuning. Berbagai penyakitpun dapat diatasi oleh nya diantaranya :\n\nanti mikroba, pencegah kanker, mengatasi penyakit maag, menurunkan kadar lemak dan kolesterol dalam darah, anti oksidan, mengatasi rasa mual, pembalut luka dan menghilangkan gatal - gatal pada kulit.\n\nSalah Satu Manfaat :\n\nMenurunkan kadar lemak dan kolesterol dalam darah adalah dengan meminum airnya yang didapat dari memarut kunyit kemudian ambil sarinya berupa air. Lakukan hingga kadar lemak dan kolesterol turun.","https://hellosehat.com/wp-content/uploads/2017/03/6-Manfaat-Kunyit-Untuk-Pencernaan-Dan-Kesehatan.jpg"  },
            {"LENGKUAS", "Deskripsi Singkat :\n\nLengkuas atau dengan nama ilmiah Alpinia galanga pasti di gunakan jika kita ingin membuat rendang. Namun tahukan kita bahwa lengkuas yang memiliki zat aktif galangol, methyl-cinnamae, galangin, sineol, kamfer, seskuiterpen, kadien, resin, heksabidrokadalen hidrat dan amilum terbukti ampuh mengatasi penyakit diantaranya : melancarkan peredaran darah, membuang toxin dan radikal bebas dalam tubuh, penambah nafsu makan, menyembuhkan rematik dan limfa, meredakan diare, mengatasi mabuk darat dan laut dan mencegah tumor.\n\n\nManfaat :\n\n\nMenjadikannya sebagai bahan bumbu masakan adalah cara efektif untuk mencegah dan mengobati berbagai penyakit atau dengan merebus 3 ruas lengkuas yang sudah diiris tipis-tipis dengan 3 gelas air hingga mendidih dan menyisakan 1/2 gelas air. Minum air rebusan tersebut diwaktu pagi sebelum sarapan.","https://www.pertanianku.com/wp-content/uploads/2019/03/Yuk-Kita-Gali-Info-Soal-Manfaat-Lengkuas-untuk-Kesehatan.jpg"  },
            {"SIRIH","Deskripsi Singkat : \n\nYang dalam bahasa latin (ilmiah) disebut Piper betle, sejak dahulu telah dimanfaatkan oleh masyarakat terutama dengan mengunyah daun atau buahnya bersama gambir, pinang, dan kapur.\n Minyak atsiri dari daun sirih memiliki kandungan minyak terbang (betIephenol), seskuiterpen, pati, diatase, gula dan zat samak dan kavikol yang memiliki daya antioksidasi (mematikan kuman) dan fungisida (anti jamur).\nSelain itu sirih juga mengandung bahan aktif fenol dan kavikol daun sirih hutan juga dapat dimanfaatkan sebagai pestisida nabati untuk mengendalikan hama penghisap.\n\nManfaat :\n\nAir rebusan tanaman obat ini (daun sirih) dipercaya dapat menghilangkan bau mulut jika dikumur-kumur. Khasiat daun sirih lainnya adalah dapat mengurangi jerawat apabila diabasuk ke muka. Sementara jika daun sirih dikonsumsi bersama pinang dan juga kapur juga dipercaya dapat menguatkan gigi sehingga tidak mudah tanggal.","https://cdn1-production-images-kly.akamaized.net/6dljYdRJD-y93NKhUzxL_5XRdx0=/750x416/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/2103654/original/093794800_1524197419-iStock-802409906.jpg"},
            {"DAUN KEMANGI","Deskripsi Singkat :\n\nKemangi atau Ocimum × citriodorum banyak sekali  makanan yg menggunakan kemangi, selain jadi lalapan, tumbuhan yang satu ini ternyata berguna sekali untuk mencegah bau mulut, sariawan, diare, nyeri payudara serta mengatasi masalah flu. Daun Kemangi mengandung sejumlah senyawa penting, diantaranya: senyawa anetol, senyawa 1-8 sineol, zat arigin, zat flavonoid, boron, stigmasterolnya, eugenol, betakaroten, magnesium, zat triptofan, dan masih banyak lagi zat- zat lainnya.\n\nManfaat :\n\nBerdasar penelitian, didapatkan hasil bahwa kegunaanya terbukti mampu mengobati perut kembung, masuk angina, kejang sampai badan lesul. Disisi lain, aroma kemangi sangat efektif sebagai obat nyamuk. Jadi cocok bila digunakan sebagai toga (tanaman obat keluarga).","https://inilahtasik.com/wp-content/uploads/2018/06/basil_leaf_and_flower.jpg"},
            {"COCOR BEBEK","Deskripsi Singkat :\n\nKandungan kimia cocor bebek antara lain zat asam lemon, zat asam apel, vitamin C, quercetin-3-diarabinoside, kaemferol-3-glikoside, dan tanin. Anggota famili Crassulaceae itu bersifat agak asam, bau lemah, dan dingin. Khasiatnya sebagai antiradang, menghentikan pendarahan, mengurangi pembengkakan dan mempercepat penyembuhan.\n\nManfaat : \n\nSeluruh bagian tanaman herbal yang segar ini bisa dimanfaatkan sebagai tanaman obat keluarga untuk mengatasi berbagai macam penyakit seperti nyeri lambung dan diare, muntah darah, rematik, disentri, diare dan demam, serta masih banyak lagi penyakit lainnya yang bisa diatasi.","https://www.deherba.com/wp-content/uploads/2019/01/Daun-Cocor-Bebek-768x384.jpg"},
            {"KUMIS KUCING","Deskripsi Singkat :\n\nKumis kucing(Orthosiphon stamineus) memiliki rasa sedikit rasa pahit, agak asin, sepat, dan bersifat sejuk. Beberapa bahan kimia yang terkandung dalam kumis kucing, di antaranya zat samak, minyak atsiri, orthosiphonglikosida, minyak lemak, saponin, sapofonin, garam kalium (0,6 – 3,5%), dan myoinositol.\n\nManfaat :\n\nkumis kucing mempunyai beberapa efek farmakologis, di antaranya menghancurkan batu di saluran kencing, diuretik (peluruh air seni) dan  antiradang. Seluruh bagian kumis kucing dapat dimanfaatkan untuk mengobati beberapa penyakit seperti batu kandung empedu, bengkak kandung kemih encok, infeksi kandung kemih (batu dalam kandung kemih).","https://sijai.com/wp-content/uploads/2017/04/Kumis-kucing-nungkinuaridewi96-wordpress-com-768x576.jpg"},
            {"LIDAH BUAYA","Deskripsi Singkat : \n\nLidah buaya adalah sejenis tumbuhan yang sudah dikenal sejak ribuan tahun silam dan digunakan sebagai penyubur rambut, penyembuh luka, dan untuk perawatan kulit. Tumbuhan ini dapat ditemukan dengan mudah di kawasan kering di Afrika. \n\nManfaat : \n\nBerdasarkan hasil penelitian, daun lidah buaya dapat berfungsi sebagai antiinflamasi, antijamur, antibakteri dan regenerasi sel. Di samping itu, lidah buaya bermanfaat  untuk menurunkan kadar gula dalam darah, menstimulasi kekebalan tubuh terhadap serangan penyakit kanker, serta dapat digunakan sebagai nutrisi pendukung bagi penderita HIV. Penggunaannya dapat berupa gel dalm bentuk segar atau dalam bentuk bahan jadi (kapsul, jus, pasta atau makanan dan minuman segar kesehatan). Bunga dan akar lidah buaya juga memiliki khasiat sebagai obat cacing dan susah buang air besar (sembelit).","https://cdn.idntimes.com/content-images/community/2019/02/aloe-vera-plants-2ad1f1be593b3961ff98f13c8e956f94_600x400.jpg"},
            {"MENIRAN","Deskripsi Singkat :\n\nKhasiat meniran (Philanthus urinaria) adalah salah satu jenis tanaman yang memiliki bentuk batang bulat, basah dan tinggi kurang dari 50 cm. Daun dari tanaman meniran bertulang menyirip genap, setiap satu tangkai memiliki daun majemuk dengan ukuran yang kecil dan berbentuk lonjong.Bunga tumbuhan ini terdapat pada setiap ketiak daun serta menghadap ke bagian bawah. Meniran umumnya tidak dipelihara, karena dianggap tumbuhan rumput biasa. Meniran tumbuh subur di tempat yang lembab pada dataran rendah sampai ketinggian 1000 meter di atas permukaan laut. Senyawa kimia yang terkandung di dalam tubuh meniran adalah zat filantin, kalium, damar dan zat penyamak. \n\nManfaat :\n\nMeniran yang paling populer di masyarakat adalah keampuhan dalam mengatasi asam urat, Jika diperhatikan, hampir semua produk-prosuk herbal anti asam urat mengguakan meniran sebagai salah satu bahan dasarnya. Berbagai sumber kesehatan menyatakan bahwa meniran bagian pada meniran bermanfaat untuk pengobatan penyakit, seperti penurun panas, pereda batuk, dan pelindung organ hati.","https://deltomed.id/uploads/posts/meniran.jpg"},
            {"PANDAN","Deskripsi Singkat : \n\nPandan wangi (Pandanus amaryllifolius) atau biasa disebut pandan saja adalah jenis tumbuhan monokotil dari famili Pandanaceae yang memiliki daun beraroma wangi yang khas. Daunnya merupakan komponen penting dalam tradisi masakan Indonesia dan negara-negara Asia Tenggara lainnya. Tumbuhan ini mudah dijumpai di pekarangan atau tumbuh liar di tepi-tepi selokan yang teduh. Akarnya besar dan memiliki akar tunggang yang menopang tumbuhan ini bila telah cukup besar. Daunnya memanjang seperti daun palem dan tersusun secara roset yang rapat, panjangnya dapat mencapai 60cm. Beberapa varietas memiliki tepi daun yang bergerigi.\n\nManfaat :\n\nTerapi dengan pandan wangi: Iris-iris 2 – 5 lembar daun pandan, lalu rebus atau seduh dengan air panas, kemudian diminum. Atau tumbuk daun pandan, lalu peras dan minum. Untuk pemakaian luar, cuci bersih daun pandan dan giling sampai halus. Balurkan pada bagian yang sakit atau kulit kepala yang berketombe, mengatasi rasa gelisah dengan daun pandan wangi: Cuci dua lembar daun pandan segar, lalu iris tipis-tipis. Seduh dengan segelas air panas. Dinginkan, kemudian saring airnya. Minum 2 – 3 kali sehari sampai merasa tenang.","https://upload.wikimedia.org/wikipedia/id/thumb/5/55/Pandan_Wangi.JPG/800px-Pandan_Wangi.JPG"},
            {"BUAH PARE","Deskripsi Singkt :\n\nPeria atau pare (Momordica Charantia L.) adalah tumbuhan merambat yang berasal dari wilayah Asia Tropis, terutama daerah India bagian barat, yaitu Assam dan Burma. Aanggota suku labu-labuan atau Cucurbitaceae ini biasa dibudidayakan untuk dimanfaatkan sebagai sayuran maupun bahan pengobatan. Nama Momordica yang melekat pada nama binomialnya berarti gigitan yang menunjukkan pemerian tepi daunnya yang bergerigi menyerupai bekas gigitan.\n\nManfaat : \n\nManfaat pare yang paling terkenal adalah menurunkan gula darah. Beberapa studi menunjukkan, mengonsumsi pare dapat menurunkan gula darah dan kadar HbA1c (pemeriksaan untuk memantau kadar gula darah selama periode tertentu) pada penderita diabetes tipe 2.","https://cdn.jitunews.com/dynamic/article/2015/10/22/23995/6ZelumjDjN.jpg?w=800"},
            {"ROSELLA","Deskripsi Singkat : \n\nTanaman Rosella (Hibiscus sabdariffa Linn.) adalah spesies bunga yang berasal dari benua Afrika. Mulanya bunga yang juga cantik untuk dijadikan penghias halaman rumah itu diseduh sebagai minuman hangat di musim dingin dan minuman dingin di musim panas. Di negeri asalnya, Afrika, rosela dijadikan selai atau jeli. Itu diperoleh dari serat yang terkandung dalam kelopak rosela\n\nManfaat :\n\ndapat digunakan untuk mencegah penyakit kanker, mengendalikan tekanan darah, melancarkan peredaran darah, dan melancarkan buang air besar, menurunkan kadar kolesterol dalam darah. Sebanyak 3 kelopak bunga rosela diseduh dengan menggunakan air yang mendidih  200 ml. Tunggu saja 5 s/d 10 menit hingga airnya berubah jadi berwarna merah, diminum 2 kali dalam dalam sehari sebelum makan. pada orang yang sakit maag diminum satu jam setelah makan.","https://www.greeners.co/wp-content/uploads/2017/04/Flora-Tanaman-Rosella-Si-Merah-yang-Penuh-Khasiat.jpg"}

    };

    public static ArrayList<Tanaman> ambilData(){
        ArrayList<Tanaman> list = new  ArrayList<>();
        for ( String[] sData : datatoga ){
            Tanaman stanaman = new Tanaman();
            stanaman.setNama( sData[0] );
            stanaman.setDetail( sData[1] );
            stanaman.setPoto( sData[2] );

            list.add( stanaman );
        }


        return list;
    }
}
